---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  # - ANSIBLE_VERSION=2.4.1.0
  # - ANSIBLE_VERSION=2.3.1.0

before_install:
  - sudo apt-get update -qq
  - chmod +x deploy/sunbird_install.sh

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; fi #else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  - bash deploy/sunbird_install.sh
 # - ./test.sh
 
