---
sudo: required
dist: trusty

language: python
python: "2.7"

addons:
  ssh_known_hosts:
  - 13.232.188.44
  - 13.127.235.204

env:
  - ANSIBLE_VERSION=latest
  # - ANSIBLE_VERSION=2.4.1.0
  # - ANSIBLE_VERSION=2.3.1.0

before_install:
  - sudo apt-get update -qq
  # - chmod +x deploy/sunbird_install.sh

install:
  # - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; fi #else pip install ansible==$ANSIBLE_VERSION; fi
  # - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
  - pip install pyyaml
  - pip install subprocess
  - pip install json
  - pip install shlex
before_script: 
- python createConfigYml.py
- echo $(readlink -f configuration.yml)
script:
  - bash install.sh
  # - echo $(readlink -f ciTestKey.pem)
  # - chmod 0400 /home/travis/build/rajeevsathish/sunbird-devops/deploy/ciTestKey.pem
  # - bash sunbird_install.sh
  # - bash sunbird_install.sh -s dbs
  # - bash sunbird_install.sh -s apis
  # - bash sunbird_install.sh -s proxy
  # - bash sunbird_install.sh -s keycloak
  # - bash sunbird_install.sh -s badger
  # - bash sunbird_install.sh -s core
 # - ./test.sh
after_success:

after_failure:
